export const SEARCH_PLACE_SUCCESS = 'SEARCH_PLACE_SUCCESS'
export const LOAD_RECENT_SEARCH_PLACE_SUCCESS = 'LOAD_RECENT_SEARCH_PLACE_SUCCESS'
export const LOAD_PLACE_DETAIL_SUCCESS = 'LOAD_PLACE_DETAIL_SUCCESS'
